[tools]
rojo = "rojo-rbx/rojo@7.4.1"
wally = "UpliftGames/wally@0.3.2"
lune = "lune-org/lune@0.8.4"
stylua = "JohnnyMorganz/StyLua@0.20.0"
selene = "Kampfkarren/selene@0.27.1"
rbxcloud = "Sleitnick/rbxcloud@0.10.0"
